### ISSUE TITLE
Update the media queries to mobile first

### ISSUE THREAD

**Issue by crysfel** [Coding-Coach/coding-coach#107]
# Issue

## ZenHub Issue

We have defined some utilities to deal with media queries, under `theme/base/_mediaquesries.scss` file we have a mixing that defines several sizes.

Update the `mixin` to be mobile first. Take a look at this tutorial if need some help: https://zellwk.com/blog/how-to-write-mobile-first-css/

**Comment by tureey** [comment]
May I do this? @crysfel

**Comment by emmawedekind** [comment]
Sure, I will add you.

**Comment by tureey** [comment]
I'll update the `mediaqueries` and then refactor all the styles in the website, since the there will be a `technical debt`.

**I'll work on this the next weekend!**

Would be good to **update tasks** and say that until this one is not finished, they should create `scss` using the `mobile first` and create the `mediaqueries` manually. *It will make the refactor easier solving conflicts.*

**Comment by crysfel** [comment]
I don't think there will be a lot of css updates coming up in the next few days. But I will make sure to request mobile first css in PRs.

**Comment by Venablena** [comment]
For me, mobile first approach didn't work. In other words: this produced the expected behavior of stacking horizontal items vertically on mobile:
`.footer {
  display: flex;
  flex-flow: row;
  justify-content: flex-end;
  text-align: right;
  @include respond-to(mobile){
    flex-flow: column;
    text-align: center;
    justify-content: center;
  };
}`

whereas this didn't:
`.footer {
  display: flex;
  flex-flow: column;
  text-align: center;
  justify-content: center;
  @include respond-to(tablet){
    flex-flow: row;
    justify-content: flex-end;
    text-align: right;
  };
}`

**Comment by tureey** [comment]
Is this comment older or newer than when we talked and you said it was solved? @Venablena

**Comment by Venablena** [comment]
@tureey It's newer.

**Comment by tureey** [comment]
@Venablena It worked for me! I updated my PR with it.

```
.footerInner {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-left: 20px;
  margin-right: 20px;
  padding: 10px 0;
  border-top: 1px solid $color-grey-light;
  
  @include respond-to(tablet) {
    flex-direction: row;
    justify-content: flex-end;
    margin-left: 30px;
    margin-right: 30px;
  };
}
```

Doing this, on low resolutions, the items are stack one under the next. In higher screens **from tablet and wider** they are one next to the another one and aligned on the right side.
