### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#122]
## Description
Implement the footer with links to respective modals.

![image.png](https://images.zenhubusercontent.com/5a3a7d108a75884b908bc2c0/ab3af15c-9408-4af5-87bd-61dee6695d3d)

**Comment by Venablena** [comment]
I'll do this.

**Comment by emmawedekind** [comment]
Assigned! Thanks!

**Comment by Venablena** [comment]
I'm done implementing and styling the footer but since the modal isn't here yet, I haven't implemented links to it.  I could create a pull request now and create a new issue for adding the modal functionality or I can stand by and wait for it. OR I can go ahead and build the modal too but I believe @linux-nerd is already working on it.

**Comment by crysfel** [comment]
In order to build the modals we need to create these three components first:

#112 
#125 <--- Would you like to take this one?
#127

**Comment by emmawedekind** [comment]
Closing as this is implemented!
