### ISSUE TITLE
Update Landing Page Buttons

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#164]
Button should link to: https://docs.google.com/forms/d/e/1FAIpQLSePvp-0FThEoJSZOFByoWu0Fgaz6Ki53H-h9p8siyDdnUkTPw/viewform

![image](https://user-images.githubusercontent.com/7671983/47450730-4a02e400-d7c6-11e8-9ac3-209d101a7408.png)

Remove button underneath header and remove Log In and Sign Up buttons.

**Comment by nitish24p** [comment]
@emmawedekind is this button type just for the landing page or we make this a reusable component?

**Comment by crysfel** [comment]
We can implement a `rounded` prop to many any button rounded like this. 

```
<Button type="primary" rounded>Join the mailing list</Button>
```

By default is `false`

Thoughts?

**Comment by emmawedekind** [comment]
I'm going to close this issue right now because this will change - we will implement a "Sign up for email list" (or something similar) section in the page flow. So this task will become obsolete.

**Comment by tureey** [comment]
I prefer to have a prop called `shape` with possible values `square` `rounded` `pill` for example. The reason it's **because enums are more maintainable than booleans**.

square-> border-radius: 0
rounded-> border-radius: 3px
pill-> border-radius: 500px/100% depending

And we have everything covered. Thoughts? @crysfel
