### ISSUE TITLE
UI shifts when a modal is opened

### ISSUE THREAD

**Issue by emmawedekind** [Coding-Coach/coding-coach#188]
Re-creation steps:
1. Click Terms & Conditions link in footer

Expected behavior: UI in the background should remain in the same position.
Actual behavior: UI in the background shifts a couple of pixels to the right.

![image](https://user-images.githubusercontent.com/7671983/47732533-ac486280-dc66-11e8-9df6-f73760fdd698.png)

![image](https://user-images.githubusercontent.com/7671983/47732542-b1a5ad00-dc66-11e8-8c28-f460f51e3af1.png)

**Comment by tureey** [comment]
Yes, that's actually made on purpose by me... I wanted to make sure we had no problems with the body scroll. It's annoying when you scroll and it affects to the body content. that's why..

To evade this, I added a class to the body called `u-overflowHidden`. this class makes:
```
.u-overflowHidden {
    height: 100vh;
    overflow: hidden;
  }
```

But if you guys think its better to do not have this "movement" on the window, just remove it ^^

**Comment by linux-nerd** [comment]
Updated and PR - #196 raised.
